### ISSUE TITLE
Elder Guardian Extraction Rituals Don't Work

### ISSUE THREAD

**Issue by si8v** [Call-Me-Doc/origins_lore_#7]
It is currently impossible to perform a successful ritual of extraction with an Elder Guardian, even when in a soul sand valley with linked pedestals holding Elder Guardian drops. This should guarantee success according to the conjuring mod documentation. This mob isn't in the banned mobs list, and the ritual works fine in creative worlds. Verified by Noble and Raspberry, player IDs 1 and 2.

**Comment by Call-Me-Doc** [comment]
shut.

**Comment by si8v** [comment]
> shut.

valid
